/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.entities.Producto;

import modelo.entities.Proveedor;
import modelo.persistencias.ProductoJpaController;
import modelo.persistencias.ProveedorJpaController;
import vistas.interfaces.Buscable;

/**
 *
 * @author Lenovo
 */
public class BuscarProveedor extends javax.swing.JFrame {
    private ProveedorJpaController daoProveedor;
    private ProductoJpaController daoProductos;
    private List<Proveedor> proveedores;
    private Proveedor elegido;
    private DefaultTableModel modelo;
    private Buscable ventanaPadre;
    
    /**
     * Creates new form BuscarProveedor
     */
    public BuscarProveedor(Buscable ventanaPadre) {
        this.ventanaPadre = ventanaPadre;
        this.daoProveedor = new ProveedorJpaController();
        this.daoProductos = new ProductoJpaController();
        initComponents();
        this.setupComponents();
        this.agregarEventos();
    }
    
    private void setupComponents(){
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        this.jpCabecera.setPreferredSize(new Dimension(400, 100));
        
        this.jlFiltros.setVisible(false);
        this.jrbNombre.setVisible(false);
        this.jrbProducto.setVisible(false);
        
        this.generarTabla();

        this.proveedores = this.daoProveedor.findProveedorEntities();
        this.llenarTabla();
    }
    
    private void generarTabla(){
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Productos");
       
        this.jtProveedores.setModel(modelo);
    }
    
    private void agregarEventos(){
        this.jbBuscar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                jbBuscarActionPerformed(e);
            }
            
        });
        
        this.jbAceptar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                jbAceptarActionPerformed(e);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpCabecera = new javax.swing.JPanel();
        jtfBuscar = new javax.swing.JTextField();
        jlFiltros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrbNombre = new javax.swing.JRadioButton();
        jrbProducto = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jpCabecera.setBackground(new java.awt.Color(102, 4, 4));
        jpCabecera.setPreferredSize(new java.awt.Dimension(400, 150));
        jpCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpCabecera.add(jtfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 190, -1));

        jlFiltros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlFiltros.setForeground(new java.awt.Color(255, 255, 255));
        jlFiltros.setText("Filtros");
        jpCabecera.add(jlFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Proveedor");
        jpCabecera.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jrbNombre.setText("Nombre");
        jpCabecera.add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jrbProducto.setText("Producto");
        jpCabecera.add(jrbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jbBuscar.setText("Buscar");
        jpCabecera.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");
        jpCabecera.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel1.add(jpCabecera, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(5, 105, 27));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAceptar.setText("Aceptar");
        jPanel4.add(jbAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 140, 30));

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jtProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Productos"
            }
        ));
        jScrollPane1.setViewportView(jtProveedores);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbBuscarActionPerformed(ActionEvent e){
        this.proveedores = this.daoProveedor.findProveedorByName(this.jtfBuscar.getText());
        this.llenarTabla();
    }
   
    private void jbAceptarActionPerformed(ActionEvent e){
        int indice = this.jtProveedores.getSelectedRow();
        this.elegido = this.proveedores.get(indice);
        this.ventanaPadre.setProveedor(this.elegido);
        this.ventanaPadre.actualizarProveedor();
        this.dispose();
    }
    
    private void llenarTabla(){
        this.generarTabla();
        String[] campos = new String[2];
        List<Producto> productos;
        for(Proveedor p : this.proveedores){
            campos[0] = p.getNombre();
            productos = this.daoProductos.findProductoByProveedor(p);
            String campoProductos = "";
            for(Producto p1 : productos){
                campoProductos += p1.getNombre() + ", ";
            }
            campos[1] = campoProductos;
            this.modelo.addRow(campos);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel jlFiltros;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbProducto;
    private javax.swing.JTable jtProveedores;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
