/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.entities.Producto;
import modelo.entities.Productos;
import modelo.persistencias.ProductoJpaController;
import vistas.interfaces.AgregandoProductos;

/**
 *
 * @author Lenovo
 */
public class BuscarProducto extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private AgregandoProductos ventanaPadre;
    private List<Producto> productos;
    private ProductoJpaController daoProductos;
    /**
     * Creates new form BuscarProdcuto
     */
    public BuscarProducto(AgregandoProductos ventanaPadre) {
        this.daoProductos = new ProductoJpaController();
        this.ventanaPadre = ventanaPadre;
        initComponents();
        this.setupComponents();
    }

    private void setupComponents(){
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.generarTabla();
        this.productos = this.daoProductos.findProductoByProveedor(this.ventanaPadre.getProveedor());
        this.llenarTabla();
        
        
        this.jsCantidad.setValue(1);
        
        
    }
    private void generarTabla(){
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Proveedor");
       
        this.jtProductos.setModel(modelo);
    }
    
    private void llenarTabla(){
        this.generarTabla();
        String[] campos = new String[3];
        for(Producto p : productos){
            campos[0] = p.getNombre();
            campos[1] = Float.toString(p.getCosto());
            campos[2] = p.getIdProveedor().getNombre();
            this.modelo.addRow(campos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtfBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbAgregar = new javax.swing.JButton();
        jsCantidad = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 4, 4));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jtfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(5, 105, 27));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 170, 30));
        jPanel4.add(jsCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, 100, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        int index = this.jtProductos.getSelectedRow();
        int cantidad = (int)this.jsCantidad.getValue();
        Producto producto = this.productos.get(index);
        double total = cantidad * producto.getCosto();
        Productos detalle = new Productos();
        detalle.setIdProducto(producto);
        detalle.setCantidad(cantidad); 
        detalle.setTotal(total);
        
        this.ventanaPadre.agregarDetalle(detalle);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        this.productos = this.daoProductos.findProductoByName(this.jtfBuscar.getText(), this.ventanaPadre.getProveedor());
        this.llenarTabla();
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JSpinner jsCantidad;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
