/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.entities.Cultivo;
import modelo.entities.Ordencompra;
import modelo.entities.Productos;
import modelo.entities.Proveedor;
import modelo.persistencias.CultivoJpaController;
import modelo.persistencias.OrdencompraJpaController;
import modelo.persistencias.ProductosJpaController;
import modelo.persistencias.exceptions.NonexistentEntityException;
import vistas.interfaces.AgregandoProductos;
import vistas.interfaces.Buscable;

/**
 *
 * @author Lenovo
 */
public class DetalleOrdenCompraFrame extends javax.swing.JFrame implements Buscable, AgregandoProductos{
    
    private DefaultTableModel modelo;
    private Ordencompra orden;
    private MotrarOrdenCompraFrame ventanaAnterior;
    private ProductosJpaController daoDetalles;
    private BuscarProveedor jpProveedor;
    private List<Productos> detalles;
    private List<Productos> detallesEliminados;
    private boolean editable;
    private CultivoJpaController daoCultivo;
    private List<Cultivo> cultivos;
    private Proveedor proveedor;
    private BuscarProducto jpProducto;
    /**
     * Creates new form DetalleOrdenCompraFrame
     */
    public DetalleOrdenCompraFrame(MotrarOrdenCompraFrame ventanaAnterior, Ordencompra orden, boolean editable){
        this.daoCultivo = new CultivoJpaController();
        this.detallesEliminados = new ArrayList();
        this.editable = editable;
        this.ventanaAnterior = ventanaAnterior;
        this.orden = orden;
        this.daoDetalles = new ProductosJpaController();
        initComponents();
        this.setupComponents();
    }
    
    private void setupComponents(){
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.jtfProveedor.setEditable(false);
        if(!this.editable){
            ((JTextField)this.jdcFecha.getComponent(1)).setEditable(false);
 
            this.jsBlock.setEnabled(false);
            
            this.jcbCultivo.removeAllItems();
            this.jcbCultivo.setEnabled(false);
            this.jbBuscar.setVisible(false);
            this.jbGuardar.setVisible(false); 
        }
        ((JTextField)this.jdcFecha.getComponent(1)).setEditable(false);
        
        this.jcbCultivo.removeAllItems();
        this.cultivos = this.daoCultivo.findCultivoEntities();
        for(Cultivo c : cultivos){
            this.jcbCultivo.addItem(c.getNombre());
        }
        
        this.proveedor = this.orden.getProveedor();
        
        this.cargarInformacion();
        
    }
    
    private void cargarInformacion(){
        this.jlTitulo.setText("Orden de compra [" + this.orden.getIdordenCompra() + "]");
        this.jdcFecha.setDate(this.orden.getFecha());
        this.jtfProveedor.setText(this.orden.getProveedor().getNombre());
        this.jsBlock.setValue(this.orden.getBlock());
        this.jcbCultivo.setSelectedItem(this.orden.getCultivo().getNombre());
        
        
        this.generarTabla();
        this.detalles = this.daoDetalles.findProductosByOrden(this.orden);
        this.llenarTabla();
    }

    private void generarTabla(){
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Total");
        this.jtProductos.setModel(modelo);
    }
    
    private void llenarTabla(){
        this.generarTabla();
        String[] campos = new String[3];
        for(Productos p : detalles){
            campos[0] = p.getIdProducto().getNombre();
            campos[1] = Integer.toString(p.getCantidad());
            campos[2] = " ";
            this.modelo.addRow(campos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jtfProveedor = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jsBlock = new javax.swing.JSpinner();
        jcbCultivo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jbEliminar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jbGuardar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 500));

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(5, 105, 27));
        jPanel2.setMinimumSize(new java.awt.Dimension(491, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("Orden de compra []");
        jPanel2.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setPreferredSize(new java.awt.Dimension(480, 276));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Fecha:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel3.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Proveedor:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jtfProveedor.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(jtfProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, -1));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Block:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel3.add(jsBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, -1));

        jcbCultivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCultivoActionPerformed(evt);
            }
        });
        jPanel3.add(jcbCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 160, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Cultivo:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel5.add(jbEliminar);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        jPanel5.add(jbAgregar);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(5, 105, 27));
        jPanel6.setPreferredSize(new java.awt.Dimension(360, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtProductos);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 370, 130));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        this.jpProveedor = new BuscarProveedor(this);
        this.jpProveedor.setVisible(true);
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcbCultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCultivoActionPerformed

    }//GEN-LAST:event_jcbCultivoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if(!this.jtfProveedor.getText().equals("")){
            int index = this.jtProductos.getSelectedRow();
            this.modelo.removeRow(index);
            this.detallesEliminados.add(this.detalles.get(index));
            this.detalles.remove(index);
        }else{
            JOptionPane.showMessageDialog(this, "Primero se debe elegir un proveedor para utilizar esta función.");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        if(!this.jtfProveedor.getText().equals("")){
            this.jpProducto = new BuscarProducto(this);
            this.jpProducto.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Primero se debe elegir un proveedor para utilizar esta función.");
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas actualizar esta orden de compra?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(opcion == JOptionPane.YES_OPTION){
            Ordencompra ordenCompra = new Ordencompra();
            ordenCompra.setIdordenCompra(this.orden.getIdordenCompra());
            ordenCompra.setFecha(this.jdcFecha.getDate());
            ordenCompra.setBlock((int)this.jsBlock.getValue());
            ordenCompra.setCultivo(this.cultivos.get(this.jcbCultivo.getSelectedIndex()));
            ordenCompra.setFolio(this.orden.getIdordenCompra());
            ordenCompra.setProveedor(this.proveedor);
            ordenCompra.setEstado("En proceso");
            double total = 0;
            for(Productos p : this.detalles){
                total += p.getTotal();
            }
            ordenCompra.setMontoTotal(total);
            OrdencompraJpaController daoOrden = new OrdencompraJpaController();
           
            try {
                daoOrden.edit(ordenCompra);
            } catch (NonexistentEntityException ex) {
                ex.printStackTrace();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            
            
            ProductosJpaController daoProductos = new ProductosJpaController();
            for(Productos p : this.detalles){
                if(daoProductos.findProductos(p.getIdProductos()) == null){
                    p.setIdOrdenCompra(ordenCompra);
                    p.setOrdenCompra(ordenCompra.getIdordenCompra());
                    daoProductos.create(p);
                }
            }
            for(Productos p: this.detallesEliminados){
                if(daoProductos.findProductos(p.getIdProductos()) != null){
                    try {
                        daoProductos.destroy(p.getIdProductos());
                    } catch (NonexistentEntityException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }
            this.dispose();
        }
        
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas cancelar la edición?", "Confirmación",  JOptionPane.YES_NO_OPTION);
        if(opcion == JOptionPane.YES_OPTION){
            this.dispose();
        }
        
    }//GEN-LAST:event_jbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbCultivo;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JSpinner jsBlock;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTextField jtfProveedor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarProveedor() {
        this.jtfProveedor.setText(this.proveedor.getNombre());
        this.detallesEliminados.addAll(this.detalles);
        this.detalles.clear();
        this.llenarTabla();
    }

    @Override
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    @Override
    public void agregarDetalle(Productos detalle) {
        this.detalles.add(detalle);
        this.generarTabla();
        this.llenarTabla();
    }

    @Override
    public Proveedor getProveedor() {
        return this.proveedor;
    }
}
